# Generated by Django 2.1.5 on 2019-01-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='suggested_locations',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
